env: {
  "node": true,
  "commonjs": true,
  "es6": true,
  "jest": true
}
extends: "eslint:recommended"
parserOptions: {
  "ecmaVersion": 2022,
  "sourceType": "module"
}
rules: {
  "no-unused-vars": "error",
  "no-console-log": "off",
  "no-var": "error",
  "no-duplicate-imports": "error"
}
