FROM arm32v7/node:slim

RUN apt-get update && \
    apt-get install -y python3 make g++ libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install sqlite3 --build-from-source --sqlite=/usr

COPY ./src ./src
CMD [ "npm", "start" ]